# docker-compose.yml - FamLink deployment with GHCR authentication
# To use this compose file, ensure you're logged into GHCR:
# export GITHUB_TOKEN=your_github_token_here
# echo $GITHUB_TOKEN | docker login ghcr.io -u pimpmypixel --password-stdin
# Then run: docker-compose up -d

services:
  famlink-app:
    image: ghcr.io/pimpmypixel/famlink:latest
    container_name: famlink-app
    restart: unless-stopped
    volumes:
      # Persistent storage
      - ./storage/app:/var/www/html/storage/app
      - ./storage/logs:/var/www/html/storage/logs
      # Environment file
      - ./.env:/var/www/html/.env:ro
    environment:
      - CONTAINER_ROLE=app
    labels:
      - "com.github.package=ghcr.io/pimpmypixel/famlink"
    networks:
      - famlink-network
      - nginx-proxy-manager
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    depends_on:
      - famlink-db

  famlink-db:
    image: postgres:16-alpine
    container_name: famlink-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: famlink
      POSTGRES_USER: famlink_user
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secure_password_change_me}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - famlink-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U famlink_user -d famlink"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
    driver: local

networks:
  famlink-network:
    driver: bridge
  nginx-proxy-manager:
    external: true